language: r

warnings_are_errors: true

# r_check_revdep: true

r_packages:
  - latticeExtra

r_github_packages:
  - hadley/devtools

notifications:
  email:
    on_success: change
    on_failure: change
